### ISSUE TITLE
Check git push rights

### ISSUE THREAD

**Issue by AndyOGo** [axa-ch/generic-release#6]
It turns out that if the user does not have `push` rights to `develop` and `master` but has publish right at NPM, this case isn't detected.

As a result things get messed up:

- we have a new published version at npm, but
- no updates for `develop` and `master` over at github
- no versioned git tag
- potential history mess ups (local new develop and tag, but not at remote and potential PRs/merges onto remote develop before release is pushed)

**Comment by AndyOGo** [comment]
`git push --dry-run` does not seem to be an option :(
https://stackoverflow.com/questions/25403573/how-can-one-dry-run-a-git-push-to-check-whether-one-has-write-permissions-to-a-r

**Comment by LucaMele** [comment]
@AndyOGo thank you for this! very good point!

**Comment by AndyOGo** [comment]
So how we could hack a check would be:

```sh
# switch to develop branch
git checkout develop
# get latest changes
git pull
# here is the magic empty commits
git commit --allow-empty -m "Trigger real permission checks"
git push
```

https://git-scm.com/docs/git-commit#git-commit---allow-empty

If above errors we have to abort the release, this should be done during NPM checks before actual building.

**Comment by AndyOGo** [comment]
will provide a PR
